name: Release

permissions:
  contents: write

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build binary
        run: cargo build --release

      - name: Stage release files
        run: |
          mkdir -p dist/bin
          mkdir -p dist/completion

          cp target/release/falsec dist/bin/
          cp completion/falsec.bash dist/completion/
          cp completion/falsec.elv dist/completion/
          cp completion/falsec.fish dist/completion/
          cp completion/falsec.zsh dist/completion/
          cp LICENSE dist/

      - name: Derive version
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create tarball
        run: tar -czf falsec-bin-${{ env.VERSION }}-x86_64.tar.gz -C dist .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: falsec-bin-${{ env.VERSION }}-x86_64.tar.gz
